apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app
  namespace: default
  labels:
    app: nginx-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-app
  template:
    metadata:
      labels:
        app: nginx-test-app
    spec:
      containers:
      - name: nginx-test-app
        image: zioposty/test-nginx:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080