apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-app
  namespace: argocd-exercise
  labels:
    app: nginx-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test-app
  template:
    metadata:
      labels:
        app: nginx-test-app
    spec:
      containers:
      - name: webserver-nginx
        image: zioposty/test-nginx:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2