apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-test-app
  name: nginx-test-service
  namespace: default
spec:
  selector:
    app: nginx-test-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  type: NodePort