apiVersion: v1
kind: Service
metadata:
  name: nginx-test-app
  namespace: nginx-test
spec:
  type: NodePort
  selector:
    app: nginx-test-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000